# Generated by Django 3.2.5 on 2021-08-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='handle',
            field=models.CharField(default='46883414805733879332862331111469', max_length=32, unique=True),
        ),
    ]
