# Generated by Django 3.2.5 on 2021-08-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='handle',
            field=models.CharField(default='@47329684296999534792700188505937', max_length=16, unique=True),
        ),
    ]
